name: Publish to NPM

on:
  push:
    branches:
      - master

jobs:
  publish-to-npm:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC
      contents: read # This is required for actions/checkout
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org/'
          package-manager-cache: false  # never use caching in release builds
      - run: yarn install
      - run: yarn lint
      - run: "echo 'const credentials = { clientId: \"${{ secrets.RPGLOGS_API_CLIENT_ID }}\", clientSecret: \"${{ secrets.RPGLOGS_API_CLIENT_SECRET }}\" }; export default credentials;' > src/credentials.ts"
      - run: yarn generate
      - run: yarn test
      - run: yarn build-all
      - uses: JS-DevTools/npm-publish@v4
        with:
          access: public

      - run: yarn docs
        env:
          INPUT_TOKEN: ''
      - run: touch docs/.nojekyll
      - name: Deploy docs 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs
